---
title: "Austin Animal Shelter Analysis"
author: "Anthony Ngo"
date: "July 28, 2019"
output: html_document
---

```{r , include=FALSE}
library(knitr)
library(ggplot2)
library(dplyr)
source("scripts/summary_info.R")

in_df <- read.csv("data/aac_intakes.csv", stringsAsFactors = F)
out_df <- read.csv("data/aac_outcomes.csv", stringsAsFactors = F)
in_out_df <- read.csv("data/aac_intakes_outcomes.csv", stringsAsFactors = F)

out_info <- summary_info_out(out_df)
in_info <- summary_info_in(in_df)
in_out_info <- summary_info_in_out(in_out_df)
```

# Preiminary Information

## Why I'm Looking at the Austin Animal Shelter Data

Austin Texas is the largest No-Kill community in the United States, provider of a large and frequently updated database, and home to the Austin Animal Shelter. As an avid believer in adopting animals from shelter's rather than from breeders, I wanted to see what trends and patterns there may be in the intake and outcomes of animals in the Austin Animal Shelter. 

## Where I got the data

The Austin Animal Shelter maintains a large dataset of all the animals coming into the Austin Animal Shelter and has been maintaing this dataset since October 1st, 2013. 

## What I want to learn about the Austin Animal Shelter

# Analysis
## Summary Analysis
## Grouped Analysis
# Visualizations
# Resources

